# Generated by Django 5.2.4 on 2025-08-19 08:18

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.ImageField(upload_to='items1/')),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phoneNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('telegramlink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='items/')),
                ('discription', models.TextField()),
            ],
        ),
    ]
