# Generated by Django 5.2.4 on 2025-08-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=100, upload_to='static/cake/img', width_field=100)),
                ('discription', models.CharField(max_length=500)),
                ('uploded_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingridents', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('extrabenefit', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='worktime',
            field=models.TextField(null=True),
        ),
    ]
