# Generated by Django 5.2.4 on 2025-08-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_gallary_special_about_location_about_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='specialname',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
