# Generated by Django 5.2.4 on 2025-08-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_special_specialname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallary',
            new_name='gallary1',
        ),
        migrations.RenameField(
            model_name='gallary1',
            old_name='discription',
            new_name='gallaryname',
        ),
    ]
