# Generated by Django 5.2.4 on 2025-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0004_rename_gallary_gallary1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary1',
            name='image',
            field=models.ImageField(upload_to='static/cake/img'),
        ),
    ]
