# Generated by Django 5.2.4 on 2025-08-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_alter_gallary1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='aboutmyself',
            field=models.TextField(null=True),
        ),
    ]
