# Generated by Django 5.2.4 on 2025-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_about_aboutmyself'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary1',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
