# Generated by Django 5.2.4 on 2025-08-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_alter_gallary1_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary1',
            name='cake_type',
            field=models.CharField(choices=[('holiday', 'holiday'), ('celebration', 'celebration'), ('cukis', 'cukis'), ('birthday', 'birthday'), ('chocoliets', 'chocoliets')], default='birthday', max_length=100, null=True),
        ),
    ]
