# Generated by Django 5.2.4 on 2025-08-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_gallary1_cake_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_type', models.CharField(choices=[('holiday', 'holiday'), ('celebration', 'celebration'), ('cukis', 'cukis'), ('birthday', 'birthday'), ('chocoliets', 'chocoliets')], default='birthday', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='img1/')),
                ('gallaryname', models.CharField(max_length=500)),
                ('uploded_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='gallary1',
        ),
    ]
