# Generated by Django 5.2.4 on 2025-08-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_gallary_delete_gallary1'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
