# Generated by Django 5.2.4 on 2025-08-26 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_about_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(default='all', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallaryy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img1/')),
                ('gallaryname', models.CharField(max_length=500)),
                ('uploded_date', models.DateField(auto_now_add=True)),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cake.category')),
            ],
        ),
        migrations.DeleteModel(
            name='gallary',
        ),
    ]
