"""
Django settings for ayn project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# ============================
# ✅ Basic Security Settings
# ============================

SECRET_KEY = 'django-insecure-nvwsa6h%p5^i0dpah@_jp#1i54%&isn_nmo3d-bjpl=7p!n1w^'
DEBUG = False  # Set to True during development to test static files
ALLOWED_HOSTS = ["*"]  # Update for production

# ============================
# ✅ Installed Apps
# ============================

INSTALLED_APPS = [
    'jazzmin',  # MUST come before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cake',  # your app
]

# ============================
# ✅ Middleware
# ============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================
# ✅ Templates
# ============================

ROOT_URLCONF = 'ayn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # ✅ Add this
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ayn.wsgi.application'

# ============================
# ✅ Database
# ============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ============================
# ✅ Password Validation
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================
# ✅ Internationalization
# ============================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ============================
# ✅ Static & Media Files
# ============================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",  # for local static files (optional)
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # ✅ Use this only once!

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================
# ✅ Default Auto Field
# ============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================
# ✅ Jazzmin Settings
# ============================

JAZZMIN_SETTINGS = {
    "site_title": "My Admin",
    "site_header": "Ayni's Dashboard",
    "welcome_sign": "Welcome to My Admin",
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Optional: to use the same image in favicon and top-left
    "site_logo_classes": "img-circle",  # Make it round
    "site_icon": "media\items\p3.jpg",
    # Remove these if you don't have apps named "myapp" and "blog"
    # "order_with_respect_to": ["myapp", "blog"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
}
